# The hello service provides a load-balancing proxy over the hello-app
# pods. By specifying the type as a 'LoadBalancer', Kubernetes Engine will
# create an external HTTP load balancer.
apiVersion: v1
kind: Service
metadata:
  name: socket-server
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: socket-server
  ports:
    - name: http-port
      port: 80
      targetPort: 8080
      protocol: TCP
